<?php
/**
 * HistoryStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.22
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace QualificationClient\Model;
use \QualificationClient\ObjectSerializer;

/**
 * HistoryStatus Class Doc Comment
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HistoryStatus
{
    /**
     * Possible values of this enum
     */
    const APPROVED = 'approved';
    const REVOKED = 'revoked';
    const CREATED = 'created';
    const PLACED_ON_PROBATION = 'placed on probation';
    const REMOVED_FROM_PROBATION = 'removed from probation';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APPROVED,
            self::REVOKED,
            self::CREATED,
            self::PLACED_ON_PROBATION,
            self::REMOVED_FROM_PROBATION,
        ];
    }
}


