<?php
/**
 * QualificationResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace QualificationClient\Model;

use \ArrayAccess;
use \QualificationClient\ObjectSerializer;

/**
 * QualificationResponse Class Doc Comment
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QualificationResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'QualificationResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'worker_id' => 'int',
        'qualification_type' => 'string',
        'lc_src' => 'string',
        'lc_tgt' => 'string',
        'rank' => 'string',
        'status' => 'string',
        'user' => '\QualificationClient\Model\QualificationResponseUser',
        'certificate' => 'string',
        'type' => 'string',
        'mtime' => '\DateTime',
        'ctime' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'worker_id' => null,
        'qualification_type' => null,
        'lc_src' => null,
        'lc_tgt' => null,
        'rank' => null,
        'status' => null,
        'user' => null,
        'certificate' => null,
        'type' => null,
        'mtime' => 'date-time',
        'ctime' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'worker_id' => 'worker_id',
        'qualification_type' => 'qualification_type',
        'lc_src' => 'lc_src',
        'lc_tgt' => 'lc_tgt',
        'rank' => 'rank',
        'status' => 'status',
        'user' => 'user',
        'certificate' => 'certificate',
        'type' => 'type',
        'mtime' => 'mtime',
        'ctime' => 'ctime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'worker_id' => 'setWorkerId',
        'qualification_type' => 'setQualificationType',
        'lc_src' => 'setLcSrc',
        'lc_tgt' => 'setLcTgt',
        'rank' => 'setRank',
        'status' => 'setStatus',
        'user' => 'setUser',
        'certificate' => 'setCertificate',
        'type' => 'setType',
        'mtime' => 'setMtime',
        'ctime' => 'setCtime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'worker_id' => 'getWorkerId',
        'qualification_type' => 'getQualificationType',
        'lc_src' => 'getLcSrc',
        'lc_tgt' => 'getLcTgt',
        'rank' => 'getRank',
        'status' => 'getStatus',
        'user' => 'getUser',
        'certificate' => 'getCertificate',
        'type' => 'getType',
        'mtime' => 'getMtime',
        'ctime' => 'getCtime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const RANK_PRO = 'pro';
    const RANK_STANDARD = 'standard';
    const RANK_UNTESTED = 'untested';
    const RANK_PROOFREAD = 'proofread';
    const RANK_SUPER_WORKER = 'super_worker';
    const STATUS_APPROVED = 'approved';
    const STATUS_REVOKED = 'revoked';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRankAllowableValues()
    {
        return [
            self::RANK_PRO,
            self::RANK_STANDARD,
            self::RANK_UNTESTED,
            self::RANK_PROOFREAD,
            self::RANK_SUPER_WORKER,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_APPROVED,
            self::STATUS_REVOKED,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['worker_id'] = isset($data['worker_id']) ? $data['worker_id'] : null;
        $this->container['qualification_type'] = isset($data['qualification_type']) ? $data['qualification_type'] : null;
        $this->container['lc_src'] = isset($data['lc_src']) ? $data['lc_src'] : null;
        $this->container['lc_tgt'] = isset($data['lc_tgt']) ? $data['lc_tgt'] : null;
        $this->container['rank'] = isset($data['rank']) ? $data['rank'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['user'] = isset($data['user']) ? $data['user'] : null;
        $this->container['certificate'] = isset($data['certificate']) ? $data['certificate'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['mtime'] = isset($data['mtime']) ? $data['mtime'] : null;
        $this->container['ctime'] = isset($data['ctime']) ? $data['ctime'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getRankAllowableValues();
        if (!in_array($this->container['rank'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'rank', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($this->container['status'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowedValues = $this->getRankAllowableValues();
        if (!in_array($this->container['rank'], $allowedValues)) {
            return false;
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($this->container['status'], $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets worker_id
     *
     * @return int
     */
    public function getWorkerId()
    {
        return $this->container['worker_id'];
    }

    /**
     * Sets worker_id
     *
     * @param int $worker_id worker_id
     *
     * @return $this
     */
    public function setWorkerId($worker_id)
    {
        $this->container['worker_id'] = $worker_id;

        return $this;
    }

    /**
     * Gets qualification_type
     *
     * @return string
     */
    public function getQualificationType()
    {
        return $this->container['qualification_type'];
    }

    /**
     * Sets qualification_type
     *
     * @param string $qualification_type qualification_type
     *
     * @return $this
     */
    public function setQualificationType($qualification_type)
    {
        $this->container['qualification_type'] = $qualification_type;

        return $this;
    }

    /**
     * Gets lc_src
     *
     * @return string
     */
    public function getLcSrc()
    {
        return $this->container['lc_src'];
    }

    /**
     * Sets lc_src
     *
     * @param string $lc_src Language source
     *
     * @return $this
     */
    public function setLcSrc($lc_src)
    {
        $this->container['lc_src'] = $lc_src;

        return $this;
    }

    /**
     * Gets lc_tgt
     *
     * @return string
     */
    public function getLcTgt()
    {
        return $this->container['lc_tgt'];
    }

    /**
     * Sets lc_tgt
     *
     * @param string $lc_tgt Language target
     *
     * @return $this
     */
    public function setLcTgt($lc_tgt)
    {
        $this->container['lc_tgt'] = $lc_tgt;

        return $this;
    }

    /**
     * Gets rank
     *
     * @return string
     */
    public function getRank()
    {
        return $this->container['rank'];
    }

    /**
     * Sets rank
     *
     * @param string $rank Rank of qualification
     *
     * @return $this
     */
    public function setRank($rank)
    {
        $allowedValues = $this->getRankAllowableValues();
        if (!is_null($rank) && !in_array($rank, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'rank', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['rank'] = $rank;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Status of qualification
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($status) && !in_array($status, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets user
     *
     * @return \QualificationClient\Model\QualificationResponseUser
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param \QualificationClient\Model\QualificationResponseUser $user user
     *
     * @return $this
     */
    public function setUser($user)
    {
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets certificate
     *
     * @return string
     */
    public function getCertificate()
    {
        return $this->container['certificate'];
    }

    /**
     * Sets certificate
     *
     * @param string $certificate URL of a worker certification file
     *
     * @return $this
     */
    public function setCertificate($certificate)
    {
        $this->container['certificate'] = $certificate;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets mtime
     *
     * @return \DateTime
     */
    public function getMtime()
    {
        return $this->container['mtime'];
    }

    /**
     * Sets mtime
     *
     * @param \DateTime $mtime mtime
     *
     * @return $this
     */
    public function setMtime($mtime)
    {
        $this->container['mtime'] = $mtime;

        return $this;
    }

    /**
     * Gets ctime
     *
     * @return \DateTime
     */
    public function getCtime()
    {
        return $this->container['ctime'];
    }

    /**
     * Sets ctime
     *
     * @param \DateTime $ctime ctime
     *
     * @return $this
     */
    public function setCtime($ctime)
    {
        $this->container['ctime'] = $ctime;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


