<?php
/**
 * QualificationType
 *
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.22
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace QualificationClient\Model;
use \QualificationClient\ObjectSerializer;

/**
 * QualificationType Class Doc Comment
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QualificationType
{
    /**
     * Possible values of this enum
     */
    const GENERAL = 'general';
    const DATA_CATEGORIZATIONS = 'data_categorizations';
    const ENTITY_ANNOTATIONS = 'entity_annotations';
    const SENTIMENT_ANALYSES = 'sentiment_analyses';
    const TRANSLATORS = 'translators';
    const TRANSCRIPTIONIST = 'transcriptionist';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GENERAL,
            self::DATA_CATEGORIZATIONS,
            self::ENTITY_ANNOTATIONS,
            self::SENTIMENT_ANALYSES,
            self::TRANSLATORS,
            self::TRANSCRIPTIONIST,
        ];
    }
}


