<?php
/**
 * Ranks
 *
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace QualificationClient\Model;
use \QualificationClient\ObjectSerializer;

/**
 * Ranks Class Doc Comment
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Ranks
{
    /**
     * Possible values of this enum
     */
    const PRO = 'pro';
    const STANDARD = 'standard';
    const UNTESTED = 'untested';
    const PROOFREAD = 'proofread';
    const SUPER_WORKER = 'super_worker';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRO,
            self::STANDARD,
            self::UNTESTED,
            self::PROOFREAD,
            self::SUPER_WORKER,
        ];
    }
}


