<?php
/**
 * QualificationTypeApi
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace QualificationClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use QualificationClient\ApiException;
use QualificationClient\Configuration;
use QualificationClient\HeaderSelector;
use QualificationClient\ObjectSerializer;

/**
 * QualificationTypeApi Class Doc Comment
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QualificationTypeApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createWorkerQualification
     *
     * Create a new qualification
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  \QualificationClient\Model\PostQualificationRequest $qualification qualification (required)
     *
     * @throws \QualificationClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \QualificationClient\Model\QualificationResponse[]
     */
    public function createWorkerQualification($worker_id, $qualification_type, $qualification)
    {
        list($response) = $this->createWorkerQualificationWithHttpInfo($worker_id, $qualification_type, $qualification);
        return $response;
    }

    /**
     * Operation createWorkerQualificationWithHttpInfo
     *
     * Create a new qualification
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  \QualificationClient\Model\PostQualificationRequest $qualification (required)
     *
     * @throws \QualificationClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \QualificationClient\Model\QualificationResponse[], HTTP status code, HTTP response headers (array of strings)
     */
    public function createWorkerQualificationWithHttpInfo($worker_id, $qualification_type, $qualification)
    {
        $returnType = '\QualificationClient\Model\QualificationResponse[]';
        $request = $this->createWorkerQualificationRequest($worker_id, $qualification_type, $qualification);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QualificationClient\Model\QualificationResponse[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QualificationClient\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createWorkerQualificationAsync
     *
     * Create a new qualification
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  \QualificationClient\Model\PostQualificationRequest $qualification (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createWorkerQualificationAsync($worker_id, $qualification_type, $qualification)
    {
        return $this->createWorkerQualificationAsyncWithHttpInfo($worker_id, $qualification_type, $qualification)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createWorkerQualificationAsyncWithHttpInfo
     *
     * Create a new qualification
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  \QualificationClient\Model\PostQualificationRequest $qualification (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createWorkerQualificationAsyncWithHttpInfo($worker_id, $qualification_type, $qualification)
    {
        $returnType = '\QualificationClient\Model\QualificationResponse[]';
        $request = $this->createWorkerQualificationRequest($worker_id, $qualification_type, $qualification);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createWorkerQualification'
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  \QualificationClient\Model\PostQualificationRequest $qualification (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createWorkerQualificationRequest($worker_id, $qualification_type, $qualification)
    {
        // verify the required parameter 'worker_id' is set
        if ($worker_id === null || (is_array($worker_id) && count($worker_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $worker_id when calling createWorkerQualification'
            );
        }
        // verify the required parameter 'qualification_type' is set
        if ($qualification_type === null || (is_array($qualification_type) && count($qualification_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $qualification_type when calling createWorkerQualification'
            );
        }
        // verify the required parameter 'qualification' is set
        if ($qualification === null || (is_array($qualification) && count($qualification) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $qualification when calling createWorkerQualification'
            );
        }

        $resourcePath = '/workers/{worker_id}/qualifications/{qualification_type}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($worker_id !== null) {
            $resourcePath = str_replace(
                '{' . 'worker_id' . '}',
                ObjectSerializer::toPathValue($worker_id),
                $resourcePath
            );
        }
        // path params
        if ($qualification_type !== null) {
            $resourcePath = str_replace(
                '{' . 'qualification_type' . '}',
                ObjectSerializer::toPathValue($qualification_type),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($qualification)) {
            $_tempBody = $qualification;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getQualificationTypes
     *
     * Get all types of qualifications
     *
     *
     * @throws \QualificationClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \QualificationClient\Model\QualificationTypeResponse[]
     */
    public function getQualificationTypes()
    {
        list($response) = $this->getQualificationTypesWithHttpInfo();
        return $response;
    }

    /**
     * Operation getQualificationTypesWithHttpInfo
     *
     * Get all types of qualifications
     *
     *
     * @throws \QualificationClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \QualificationClient\Model\QualificationTypeResponse[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getQualificationTypesWithHttpInfo()
    {
        $returnType = '\QualificationClient\Model\QualificationTypeResponse[]';
        $request = $this->getQualificationTypesRequest();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QualificationClient\Model\QualificationTypeResponse[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QualificationClient\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getQualificationTypesAsync
     *
     * Get all types of qualifications
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQualificationTypesAsync()
    {
        return $this->getQualificationTypesAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getQualificationTypesAsyncWithHttpInfo
     *
     * Get all types of qualifications
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQualificationTypesAsyncWithHttpInfo()
    {
        $returnType = '\QualificationClient\Model\QualificationTypeResponse[]';
        $request = $this->getQualificationTypesRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getQualificationTypes'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getQualificationTypesRequest()
    {

        $resourcePath = '/qualifications';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateWorkerQualification
     *
     * Update qualification
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  int $qualification_id Qualification ID. (required)
     * @param  \QualificationClient\Model\QualificationRequest $qualification qualification (required)
     *
     * @throws \QualificationClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \QualificationClient\Model\QualificationResponse
     */
    public function updateWorkerQualification($worker_id, $qualification_type, $qualification_id, $qualification)
    {
        list($response) = $this->updateWorkerQualificationWithHttpInfo($worker_id, $qualification_type, $qualification_id, $qualification);
        return $response;
    }

    /**
     * Operation updateWorkerQualificationWithHttpInfo
     *
     * Update qualification
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  int $qualification_id Qualification ID. (required)
     * @param  \QualificationClient\Model\QualificationRequest $qualification (required)
     *
     * @throws \QualificationClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \QualificationClient\Model\QualificationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateWorkerQualificationWithHttpInfo($worker_id, $qualification_type, $qualification_id, $qualification)
    {
        $returnType = '\QualificationClient\Model\QualificationResponse';
        $request = $this->updateWorkerQualificationRequest($worker_id, $qualification_type, $qualification_id, $qualification);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QualificationClient\Model\QualificationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\QualificationClient\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateWorkerQualificationAsync
     *
     * Update qualification
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  int $qualification_id Qualification ID. (required)
     * @param  \QualificationClient\Model\QualificationRequest $qualification (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateWorkerQualificationAsync($worker_id, $qualification_type, $qualification_id, $qualification)
    {
        return $this->updateWorkerQualificationAsyncWithHttpInfo($worker_id, $qualification_type, $qualification_id, $qualification)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateWorkerQualificationAsyncWithHttpInfo
     *
     * Update qualification
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  int $qualification_id Qualification ID. (required)
     * @param  \QualificationClient\Model\QualificationRequest $qualification (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateWorkerQualificationAsyncWithHttpInfo($worker_id, $qualification_type, $qualification_id, $qualification)
    {
        $returnType = '\QualificationClient\Model\QualificationResponse';
        $request = $this->updateWorkerQualificationRequest($worker_id, $qualification_type, $qualification_id, $qualification);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateWorkerQualification'
     *
     * @param  int $worker_id ID of a worker (required)
     * @param  string $qualification_type Qualification type. (required)
     * @param  int $qualification_id Qualification ID. (required)
     * @param  \QualificationClient\Model\QualificationRequest $qualification (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateWorkerQualificationRequest($worker_id, $qualification_type, $qualification_id, $qualification)
    {
        // verify the required parameter 'worker_id' is set
        if ($worker_id === null || (is_array($worker_id) && count($worker_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $worker_id when calling updateWorkerQualification'
            );
        }
        // verify the required parameter 'qualification_type' is set
        if ($qualification_type === null || (is_array($qualification_type) && count($qualification_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $qualification_type when calling updateWorkerQualification'
            );
        }
        // verify the required parameter 'qualification_id' is set
        if ($qualification_id === null || (is_array($qualification_id) && count($qualification_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $qualification_id when calling updateWorkerQualification'
            );
        }
        // verify the required parameter 'qualification' is set
        if ($qualification === null || (is_array($qualification) && count($qualification) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $qualification when calling updateWorkerQualification'
            );
        }

        $resourcePath = '/workers/{worker_id}/qualifications/{qualification_type}/{qualification_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($worker_id !== null) {
            $resourcePath = str_replace(
                '{' . 'worker_id' . '}',
                ObjectSerializer::toPathValue($worker_id),
                $resourcePath
            );
        }
        // path params
        if ($qualification_type !== null) {
            $resourcePath = str_replace(
                '{' . 'qualification_type' . '}',
                ObjectSerializer::toPathValue($qualification_type),
                $resourcePath
            );
        }
        // path params
        if ($qualification_id !== null) {
            $resourcePath = str_replace(
                '{' . 'qualification_id' . '}',
                ObjectSerializer::toPathValue($qualification_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($qualification)) {
            $_tempBody = $qualification;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
