<?php
/**
 * PreferredTranslatorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QualificationClient;

/**
 * PreferredTranslatorTest Class Doc Comment
 *
 * @category    Class
 * @description PreferredTranslator
 * @package     QualificationClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PreferredTranslatorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PreferredTranslator"
     */
    public function testPreferredTranslator()
    {
    }

    /**
     * Test attribute "lc_src"
     */
    public function testPropertyLcSrc()
    {
    }

    /**
     * Test attribute "lc_tgt"
     */
    public function testPropertyLcTgt()
    {
    }

    /**
     * Test attribute "rank"
     */
    public function testPropertyRank()
    {
    }

    /**
     * Test attribute "ids"
     */
    public function testPropertyIds()
    {
    }
}
