<?php
/**
 * WorkerQualificationsHistoryResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.22
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QualificationClient;

/**
 * WorkerQualificationsHistoryResponseTest Class Doc Comment
 *
 * @category    Class
 * @description WorkerQualificationsHistoryResponse
 * @package     QualificationClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WorkerQualificationsHistoryResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WorkerQualificationsHistoryResponse"
     */
    public function testWorkerQualificationsHistoryResponse()
    {
    }

    /**
     * Test attribute "qualification_type"
     */
    public function testPropertyQualificationType()
    {
    }

    /**
     * Test attribute "qualification_id"
     */
    public function testPropertyQualificationId()
    {
    }

    /**
     * Test attribute "ctime"
     */
    public function testPropertyCtime()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
