<?php
/**
 * QualificationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace QualificationClient;

use \QualificationClient\Configuration;
use \QualificationClient\ApiException;
use \QualificationClient\ObjectSerializer;

/**
 * QualificationApiTest Class Doc Comment
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QualificationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createWorkerQualification
     *
     * Create a new qualification.
     *
     */
    public function testCreateWorkerQualification()
    {
    }

    /**
     * Test case for getQualificationTypes
     *
     * Get all types of qualifications.
     *
     */
    public function testGetQualificationTypes()
    {
    }

    /**
     * Test case for getQualifications
     *
     * Get all qualifications of the given qualification type.
     *
     */
    public function testGetQualifications()
    {
    }

    /**
     * Test case for revokeWorkerQualification
     *
     * Revoke worker qualification.
     *
     */
    public function testRevokeWorkerQualification()
    {
    }

    /**
     * Test case for unrevokeWorkerQualification
     *
     * Unrevoke worker qualification.
     *
     */
    public function testUnrevokeWorkerQualification()
    {
    }

    /**
     * Test case for updateWorkerQualification
     *
     * Update qualification.
     *
     */
    public function testUpdateWorkerQualification()
    {
    }
}
