<?php
/**
 * WorkerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * qualification-client
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.22
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace QualificationClient;

use \QualificationClient\Configuration;
use \QualificationClient\ApiException;
use \QualificationClient\ObjectSerializer;

/**
 * WorkerApiTest Class Doc Comment
 *
 * @category Class
 * @package  QualificationClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WorkerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createWorker
     *
     * Create a new worker.
     *
     */
    public function testCreateWorker()
    {
    }

    /**
     * Test case for createWorkerDomain
     *
     * Add a worker specialization.
     *
     */
    public function testCreateWorkerDomain()
    {
    }

    /**
     * Test case for getWorkerQualifications
     *
     * Get worker qualifications.
     *
     */
    public function testGetWorkerQualifications()
    {
    }

    /**
     * Test case for getWorkers
     *
     * Get workers.
     *
     */
    public function testGetWorkers()
    {
    }
}
